config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  namespace :admin, path: 'a' do
    authenticated :admin do
      root 'dashboard#index'
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      get '/a/sign_out', to: 'devise/sessions#destroy', as: :delete
      resources :students
      resources :klasses do
        resources :attendances, controller: '/admin/attendances'
        get 'disable_student', to: 'klasses#disable_student'
        get 'disable', to: 'klasses#disable'
        get 'absences/:student_id', to: 'klasses#absences', as: :absences
      end
      # resources :situations
      resources :teachers
      resources :justifications, except: %i[new create]
    end
  end

  namespace :student, path: 's' do
    authenticated :student do
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      resources :justifications, only: %i[index show new create]
    end
  end

  devise_for :students, path: 's', controllers: { sessions: 'sessions',
                                                  registrations: 'registrations',
                                                  confirmations: 'student/confirmation' }
  devise_for :admins, path: 'a', controllers: { sessions: 'sessions',
                                                registrations: 'registrations'}
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  has_and_belongs_to_many :students
  has_and_belongs_to_many :klasses
  validates :name, presence: true
end

app/controllers/admin/attendances_controller.rb
# frozen_string_literal: true

class Admin::AttendancesController < AdminController
  layout 'internal'

  def index
    @klass = Klass.find_by(id: params[:klass_id])
    @attendances = @klass.attendances.order(realized_at: :desc)
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def new
    @attendance = Attendance.new
    @klass = Klass.find_by(id: params[:klass_id])
  end

  def create
    @attendance = Attendance.new(attendance_params)

    if @attendance.save
      flash[:success] = 'Attendance was created succesfully.'
      redirect_to admin_klass_attendances_path
    else
      flash[:error] = 'Something went wrong.'
      render :new
    end
  end

  def edit
    @attendance = Attendance.find(params[:id])
    @klass = Klass.find_by(id: params[:klass_id])
  end

  def update
    @attendance = Attendance.find(params[:id])

    if @attendance.update(attendance_params)
      flash[:success] = 'The attendance was updated succesfully.'
      redirect_to admin_klass_attendances_path(@attendance.klasses.first.id)
    else
      render :edit
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    flash['success'] = 'Attendance was removed successfully.'
    redirect_to admin_klass_attendances_path
  end

  private

  def attendance_params
    params.require(:attendance).permit(:name, :realized_at, klass_ids: [], student_ids: [])
  end
end

app/views/admin/attendances/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for [:admin, :klass, @attendance] do |f| %>
    <div class="form-group">
      <div class="col-md-10">
        <%= f.input :name %>
      </div>
      <div class="col-md-10">
        <%= f.input :realized_at, as: :date, label: 'Data da Aula' %>
      </div>
      <div class="col-md-10">
        <%= f.association :klasses, label: 'Turma', as: :check_boxes, checked: params[:klass_id], input_html: { multiple: true } %>
      </div>
      <div class="col-md-10">
        <%= f.association :students, label: 'Alunos', collection: @klass&.active_students, as: :check_boxes, input_html: { multiple: true } %>
      </div>
    </div>
    <%= f.submit 'Salvar', class: "btn btn-success" %>
    <%= link_to 'Voltar', :back, class: "btn btn-link" %>
    <% end %>
  </div>
</div>

app/views/admin/attendances/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="m-b-20 header-title">Editar lista</h4>
        <%= render 'form' %>
      </div>
      <!-- container -->
    </div>
  </div>
</div>

app/views/admin/attendances/index.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="header-title m-t-0 m-b-20">Aulas -  <%= link_to 'Cadastrar nova aula', new_admin_klass_attendance_path(klass_id: params[:klass_id], id: @attendance), class: 'btn btn-success btn-sm' %></h4>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="table-responsive">
          <table id="datatable" class="table table-bordered">
            <% if @attendances.empty? %>
              <p class="text-muted font-13 m-b-30">
                Nenhuma lista vinculada a esta turma!
              </p>
            <% else %>
              <thead>
                <tr><th>Turma: <%= @klass.name %></th></tr>

                <tr>
                  <th>Assunto da Aula</th>
                  <th>Data da Realização</th>
                  <th>Ação</th>
                </tr>
              </thead>

              <tbody>
                <% @attendances.each do |attendance| %>
                  <tr>
                    <td><%= attendance.name %></td>
                    <td><%= l(attendance.realized_at, format: :only_date) %></td>
                    <td><%= link_to 'Lista de presença', admin_klass_attendance_path(klass_id: params[:klass_id], id: attendance), class: 'btn btn-info btn-sm' %>
                    <%= link_to 'Editar', edit_admin_klass_attendance_path(klass_id: params[:klass_id], id: attendance), class: 'btn btn-success btn-sm' %>
                    <%= link_to 'Excluir', admin_klass_attendance_path(klass_id: params[:klass_id], id: attendance), class: 'btn btn-danger btn-sm',  data: { confirm: 'Tem certeza?' }, method: :delete %>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          </table>
        </div>
      </div>
    </div> <!-- end row -->
  </div> <!-- container -->

  <!-- Footer -->
  <div class="footer">
    <%= render 'common/footer' %>
  </div>
  <!-- END Footer -->
</div>

app/views/admin/attendances/new.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="m-b-20 header-title">Nova lista de presença</h4>
        <%= render 'form' %>
      </div>
      <!-- container -->
    </div>
  </div>
</div>

app/views/admin/attendances/show.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="m-b-20 header-title">Detalhes da lista</h4>

        <div class="form-group">
          <div class="col-md-10">
            <label>Aula:
            </label>
            <%= @attendance.name %>
          </div>
          <div class="col-md-10">
            <label>Turma:
            </label>
            <tr>
            <% @attendance.klasses.each do |klass| %>
              <td><%= klass.name %></td>
            <% end %>
            </tr>
          </div>
          <div class="col-md-10">
            <label>Lista de alunos:
            </label>
          </div>
          <div class="col-md-10">
            <table class="table table-striped">
                <tbody>
                    <% @attendance.students.each do |student| %>
                    <tr class="font-13">
                      <td><%= student.name %></td>
                      <td> Presente </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
          </div>
        <div class="col-md-10">
          <%= link_to 'Editar', edit_admin_klass_attendance_path(klass_id: params[:klass_id], id: @attendance), class: "btn btn-success" %>
          <%= link_to 'Voltar', :back, class: "btn btn-link" %>
        </div>
      </div>
      <!-- container -->
    </div>
  </div>
</div>