config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  namespace :admin, path: 'a' do
    authenticated :admin do
      root 'dashboard#index'
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      get '/a/sign_out', to: 'devise/sessions#destroy', as: :delete
      resources :students
      resources :klasses do
        resources :attendances, controller: '/admin/attendances'
        get 'disable_student', to: 'klasses#disable_student'
        get 'disable', to: 'klasses#disable'
        get 'absences/:student_id', to: 'klasses#absences', as: :absences
      end
      # resources :situations
      resources :teachers
      resources :justifications, except: %i[new create]
    end
  end

  namespace :student, path: 's' do
    authenticated :student do
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      resources :justifications, only: %i[index show new create]
    end
  end

  devise_for :students, path: 's', controllers: { sessions: 'sessions',
                                                  registrations: 'registrations',
                                                  confirmations: 'student/confirmation' }
  devise_for :admins, path: 'a', controllers: { sessions: 'sessions',
                                                registrations: 'registrations'}
end

app/controllers/admin/klasses_controller.rb
# frozen_string_literal: true

class Admin::KlassesController < AdminController
  layout 'internal'
  before_action :set_klass, except: %i[index new create]

  def index
    @klasses = Klass.all
  end

  def show
    @attendances = @klass.attendances.all
  end

  def new
    @klass = Klass.new
  end

  def create
    @klass = Klass.new(klass_params)

    if @klass.save
      flash[:notice] = 'Turma criada com sucesso!'
      redirect_to admin_klasses_path
    else
      flash[:alert] = 'Algo deu errado, verifique se você não esqueceu de preencher algo!'
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @klass.update(klass_params)
      flash[:notice] = 'A turma foi atualizada com sucesso!'
      redirect_to admin_klasses_path
    else
      render :edit
    end
  end

  def disable_student
    @klass.disable_student(params[:student_id])
    redirect_to admin_klasses_path
  end

  def disable
    @klass.disable
    flash[:notice] = 'A turma foi desativada com sucesso!'
    redirect_to admin_klasses_path
  end

  def absences
    @student = @klass.students.find(params[:student_id])
    @attendances = @klass.attendances.all
    @details = student_details

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @klass.destroy

    flash[:notice] = 'Turma excluída com sucesso!'
    redirect_to admin_klasses_path
  end

  private

  def klass_params
    params.require(:klass).permit(:name, teacher_ids: [], student_ids: [])
  end

  def set_klass
    @klass = Klass.find(params[:klass_id] || params[:id])
  end

  def student_details
    {
      klasses: @student.show_attendances(@attendances, @klass.id),
      absences: @student.count_presence(@attendances, @klass.id),
      justifications: @student.check_justifications(@klass.id, @student.email)
    }
  end
end

app/views/admin/klasses/_absences.html.erb
<div class="modal-header">
  <h5 class="modal-title" id="historyModalLabel">Faltas</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div class="modal-body">
  <strong><p><%= @student.name %></p></strong>
  <div class="row">
    <div class="col-md-4">Faltas:</div>
    <div class="col-md-6"><strong><%= @details[:absences] %></strong></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">Justificativas Aceitas:</div>
    <div class="col-md-6"> <strong><%= @details[:justifications] %></strong></div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-4">Total:</div>
    <div class="col-md-6"><strong><span class="text-danger"><%= @details[:absences] - @details[:justifications] %></span></strong></div>
  </div>
  <br>

  <% if @details[:klasses].present? %>
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
          <table class="table table-sm table-stripped">
            <thead>
              <th>Aula</th>
              <th>Data</th>
            </thead>
            <tbody>
              <% @details[:klasses].each do |klass| %>
                <tr>
                  <td><%= klass[:name] %></td>
                  <td><%= klass[:realized_at] %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
</div>

app/views/admin/klasses/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= simple_form_for [:admin, @klass] do |f| %>
    <div class="form-group">
      <div class="col-md-6">
        <%= f.input :name, label: 'Nome' %>
      </div>
      <div class="col-md-12">
        <%= f.association :teachers, label: 'Professores', as: :check_boxes, input_html: { multiple: true } %>
      </div>
      <div class="col-12">
        <div class="table-responsive">
          <table id="datatable"
                 class="table table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Ação</th>
              </tr>
            </thead>
            <tbody>
              <% @klass.students.sort_by(&:name).each do |student| %>
              <tr>
                <td>
                  <%= student.name %>
                </td>
                <td>
                  <% if student.situations.where(klass_id: @klass.id).empty? %>
                  <%= link_to 'Desativar', admin_klass_disable_student_path(klass_id: @klass.id, student_id: student), class: 'btn btn-danger btn-sm', data: { confirm: 'Tem certeza que deseja desativar este aluno?' }  %>
                  <% else %>
                  Desativado
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <%= f.submit 'Salvar', class: "btn btn-success" %>
    <%= link_to 'Voltar', :back, class: "btn btn-link" %>
    <% end %>
  </div>
</div>

app/views/admin/klasses/absences.js.erb
$("#absenceModal").find(".modal-content").html("<%= j (render 'absences') %>");
$("#absenceModal").modal();

app/views/admin/klasses/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="m-b-20 header-title">Editar turma</h4>
        <%= render 'form' %>
      </div>
      <!-- container -->
    </div>
  </div>
</div>

app/views/admin/klasses/index.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="header-title m-t-0 m-b-20">Turmas</h4>
      </div>
    </div>

    <div class="row">
      <div class="col-12">
        <div class="table-responsive">
          <table id="datatable" class="table table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data de criação</th>
                <th>Situação</th>
                <th>Ação</th>
              </tr>
            </thead>

                    <tbody>
                        <% @klasses.each do |klass| %>
                        <tr>
                            <td><%= klass.name %></td>
                            <td><%= klass.created_at.strftime("%d-%m-%Y") %></td>
                            <td><%= label_for_active(klass.active) %></td>
                            <td><%= link_to 'Aulas', admin_klass_attendances_path(klass), class: 'btn btn-warning btn-sm' %>
                                <%= link_to 'Detalhes', admin_klass_path(klass), class: 'btn btn-info btn-sm' %>
                                <%= link_to 'Editar', edit_admin_klass_path(klass), class: 'btn btn-success btn-sm' %>
                                <%= link_to 'Desativar', admin_klass_disable_path(klass), class: 'btn btn-primary btn-sm',  data: { confirm: 'Você vai desativar a turma, tem certeza?' } %>
                                <%= link_to 'Excluir', admin_klass_path(klass), class: 'btn btn-danger btn-sm',  data: { confirm: 'Você vai EXCLUIR a turma, tem certeza?' }, method: :delete %>
                        </tr>
                        <% end %>
                    </tbody>
                  </table>
              </div>
          </div>
        </div>
      </div>
      <!-- end row -->
  <!-- container -->

  <!-- Footer -->
  <div class="footer">
    <%= render 'common/footer' %>
  </div>
  <!-- END Footer -->
</div>

app/views/admin/klasses/new.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <h4 class="m-b-20 header-title">Nova turma</h4>
        <%= render 'form' %>
      </div>
      <!-- container -->
    </div>
  </div>
</div>

app/views/admin/klasses/show.html.erb
<!-- Start content -->
<div class="content">
  <div class="container-fluid">
    <h4 class="m-b-20 header-title">Detalhes da turma</h4>
    <div class="row m-b-20">
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Nome</h5>
            <p class="card-text"><%= @klass.name %></p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Professor(a)</h5>
            <p class="card-text"><%= @klass.teachers.map(&:name).to_sentence %></p>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Total de Aulas</h5>
            <p class="card-text"><%= @klass.attendances.size %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="table-responsive">
          <table id="datatable-without-buttons" class="table table-bordered">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Situação</th>
                <th>Faltas</th>
              </tr>
            </thead>
            <tbody>
              <% @klass.students.sort_by(&:name).each do |student| %>
                <tr>
                  <td>
                    <%= student.name %>
                  </td>
                  <td align="center">
                    <%= student.situations.where(klass_id: @klass.id).empty? ? label_for_klass_student_status('ativo') : label_for_klass_student_status('desativado') %>
                  </td>
                  <td>
                    <div class="col-lg-12">
                      <%= link_to 'Visualizar', admin_klass_absences_path(@klass, student), class: 'btn btn-sm btn-default', remote: true, 'data-toggle': "modal", 'data-target': '#absenceModal' %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-10">
        <%= link_to 'Editar', edit_admin_klass_path(@klass), class: "btn btn-success" %>
        <%= link_to 'Voltar', :back, class: "btn btn-link" %>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div id="absenceModal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content"></div>
  </div>
</div>
<!-- Modal -->