config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  namespace :admin, path: 'a' do
    authenticated :admin do
      root 'dashboard#index'
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      get '/a/sign_out', to: 'devise/sessions#destroy', as: :delete
      resources :students
      resources :klasses do
        resources :attendances, controller: '/admin/attendances'
        get 'disable_student', to: 'klasses#disable_student'
        get 'disable', to: 'klasses#disable'
        get 'absences/:student_id', to: 'klasses#absences', as: :absences
      end
      # resources :situations
      resources :teachers
      resources :justifications, except: %i[new create]
    end
  end

  namespace :student, path: 's' do
    authenticated :student do
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      resources :justifications, only: %i[index show new create]
    end
  end

  devise_for :students, path: 's', controllers: { sessions: 'sessions',
                                                  registrations: 'registrations',
                                                  confirmations: 'student/confirmation' }
  devise_for :admins, path: 'a', controllers: { sessions: 'sessions',
                                                registrations: 'registrations'}
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/views/home/index.html.erb
<section>
  <div class="container">
    <div class="row" align="center">
      <div class="col-sm-12">

        <div class="wrapper-page">
          <div align="center">
            <%= image_tag('aguasdearuanda', height: '120') %>
          </div>
          <div class="col-md-6">
            <%= link_to new_student_session_path do %>
            <div class="m-t-30 card-box">
              <div class="text-center">
                <h2 class="text m-t-0 m-b-30">
                  <span><%= image_tag('students-icon', height: '100') %></span>
                </h2>
                <h6 class="text-uppercase font-bold m-b-0">Aluno</h6>
              </div>
            </div>
            <% end %>
        </div>

        <div class="col-md-6">
          <%= link_to new_admin_session_path do %>
          <div class="m-t-30 card-box">
            <div class="text-center">
              <h2 class="text-uppercase m-t-0 m-b-30">
                <span><%= image_tag('admin-logo', height: '100') %></span>
              </h2>
              <h6 class="text-uppercase font-bold m-b-0">Administrador</h6>
            </div>
          </div>
          <% end %>
          </div>
          <!-- end card-box-->
        </div>
        <!-- end wrapper -->

      </div>
    </div>
  </div>
</section>