config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  namespace :admin, path: 'a' do
    authenticated :admin do
      root 'dashboard#index'
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      get '/a/sign_out', to: 'devise/sessions#destroy', as: :delete
      resources :students
      resources :klasses do
        resources :attendances, controller: '/admin/attendances'
        get 'disable_student', to: 'klasses#disable_student'
        get 'disable', to: 'klasses#disable'
        get 'absences/:student_id', to: 'klasses#absences', as: :absences
      end
      # resources :situations
      resources :teachers
      resources :justifications, except: %i[new create]
    end
  end

  namespace :student, path: 's' do
    authenticated :student do
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
      resources :justifications, only: %i[index show new create]
    end
  end

  devise_for :students, path: 's', controllers: { sessions: 'sessions',
                                                  registrations: 'registrations',
                                                  confirmations: 'student/confirmation' }
  devise_for :admins, path: 'a', controllers: { sessions: 'sessions',
                                                registrations: 'registrations'}
end

app/views/common/_admin_left_side_nav.html.erb
<div class="user-details">
  <div class="user-info">
    <a href="#"><%= current_admin.name %> </a>
    <p class="text-muted m-0">Administrador</p>
  </div>
</div>

<!--- Sidemenu -->
<div id="sidebar-menu">
  <!-- Left Menu Start -->
  <ul class="metismenu" id="side-menu">
    <li class="menu-title">Navegação</li>
    <li>
      <%= link_to admin_dashboard_path do %>
      <i class="ti-home"></i> <span> Dashboard </span>
      <% end %>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-receipt"></i> <span> Justificativas </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Listar todas', admin_justifications_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-light-bulb"></i> <span> Turmas </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar turma', new_admin_klass_path %></li>
        <li><%= link_to 'Lista de turmas', admin_klasses_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-pencil-alt"></i><span> Alunos </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar aluno(a)', new_admin_student_path %></li>
        <li><%= link_to 'Lista de alunos', admin_students_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-light-bulb"></i> <span> Professores </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar Professor(a)', new_admin_teacher_path %></li>
        <li><%= link_to 'Lista de Professores', admin_teachers_path %></li>
      </ul>
    </li>
  </ul>

</div>
<!-- Sidebar -->
<div class="clearfix"></div>

app/views/common/_admin_nav.html.erb
<div class="user-details">
  <div class="user-info">
    <a href="#"><%= current_admin.name %> </a>
    <p class="text-muted m-0">Administrador</p>
  </div>
</div>

<!--- Sidemenu -->
<div id="sidebar-menu">
  <!-- Left Menu Start -->
  <ul class="metismenu" id="side-menu">
    <li class="menu-title">Navegação</li>
    <li>
      <%= link_to admin_dashboard_path do %>
      <i class="ti-home"></i> <span> Dashboard </span>
      <% end %>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-receipt"></i> <span> Justificativas </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Listar todas', admin_justifications_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-light-bulb"></i> <span> Turmas </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar turma', new_admin_klass_path %></li>
        <li><%= link_to 'Lista de turmas', admin_klasses_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-pencil-alt"></i><span> Alunos </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar aluno(a)', new_admin_student_path %></li>
        <li><%= link_to 'Lista de alunos', admin_students_path %></li>
      </ul>
    </li>

    <li>
      <a href="javascript: void(0);"><i class="ti-light-bulb"></i> <span> Professores </span> <span class="menu-arrow"></span></a>
      <ul class="nav-second-level" aria-expanded="false">
        <li><%= link_to 'Cadastrar Professor(a)', new_admin_teacher_path %></li>
        <li><%= link_to 'Lista de Professores', admin_teachers_path %></li>
      </ul>
    </li>
  </ul>

</div>
<!-- Sidebar -->
<div class="clearfix"></div>

app/views/common/_footer.html.erb
<div>
  <strong>Águas de Aruanda</strong>
  - Copyright © 2018
</div>

app/views/common/_navs.html.erb
<%= render "common/#{user_context}_nav" %>

app/views/common/_student_nav.html.erb
<div class="user-details">
  <div class="user-info">
    <a href="#">
      <%= current_student.name %> </a>
    <p class="text-muted m-0">Estudante</p>
  </div>
</div>

<!--- Sidemenu -->
<div id="sidebar-menu">
  <!-- Left Menu Start -->
  <ul class="metismenu"
      id="side-menu">
    <li class="menu-title">Navegação</li>
    <li>
      <%= link_to student_dashboard_path do %>
      <i class="ti-home"></i> <span> Dashboard </span>
      <% end %>
    </li>

    <li>
      <%= link_to student_justifications_path do %>
      <i class="ti-receipt"></i> <span> Justificativas </span>
      <% end %>
    </li>
  </ul>

</div>
<!-- Sidebar -->
<div class="clearfix"></div>

app/views/common/_top_bar_nav.html.erb
<!-- LOGO -->
<div class="topbar-left">
  <a href="/a"
     class="logo">
    <span>
      <%= image_tag('aguasdearuanda', height: 65) %></span>
    <i>
      <%= image_tag('aguasdearuanda-sm', height: 42) %>
    </i>
  </a>
</div>

<nav class="navbar-custom">

  <ul class="list-unstyled topbar-right-menu float-right mb-0">

    <li class="dropdown notification-list">
      <a class="nav-link dropdown-toggle waves-effect waves-light nav-user"
         data-toggle="dropdown"
         href="#"
         role="button"
         aria-haspopup="false"
         aria-expanded="false">
        <%#= image_tag 'users/avatar-1', class: 'rounded-circle' %>
        <span class="ml-1">
          <%= current_user.name %> <i class="mdi mdi-chevron-down"></i> </span>
      </a>
      <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
        <!-- item-->
          <%= link_to url_for([:edit, :"#{user_context}", :registration]), class: 'dropdown-item notify-item' do %>
            <i class="ti-user"></i>
            <span>Alterar Senha</span>
          <% end %>

        <!-- item-->
        <%= link_to url_for([:destroy, :"#{user_context}", :session]), class: 'dropdown-item notify-item', method: :delete do %>
        <i class="ti-power-off"></i>
        <span>Sair</span>
        <% end %>
      </div>
    </li>
  </ul>

  <ul class="list-inline menu-left mb-0">
    <li class="float-left">
      <button class="button-menu-mobile open-left waves-light waves-effect">
        <i class="mdi mdi-menu"></i>
      </button>
    </li>
  </ul>
</nav>